MSCFBError: new macro and function for supporting error checking. MSCFBFile: update to use new error checking MSDRMMessage: update to use new error checking MSCFBTests: update to consume all documents and resources that are part of the test bundle